In [1]:
import numpy as np


In [2]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
np.arange(5,17)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [9]:
np.arange(5,100,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros(9,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones(99,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [14]:
np.zeros((3,4),int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [15]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [16]:
np.linspace(7,77,11)

array([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70., 77.])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
import numpy as np

In [23]:
np.random.rand(4,5)

array([[0.97854725, 0.50659014, 0.66562908, 0.78351938, 0.27051031],
       [0.16893102, 0.46804391, 0.85555112, 0.17272642, 0.75935335],
       [0.91033347, 0.50795142, 0.41770727, 0.44059848, 0.89782469],
       [0.13201136, 0.25702188, 0.31471888, 0.87434374, 0.86807708]])

In [25]:
np.random.randn(4,5)

array([[ 1.07338269, -1.41211949, -0.71065435,  0.62848201,  1.36797774],
       [-0.43307114, -0.1991478 , -1.82297448, -0.04601332, -1.37152617],
       [-0.67727652,  1.76948816, -1.17218848,  1.58100939,  2.54868684],
       [-0.3511771 , -0.8749314 ,  0.79680696,  0.40462401, -0.12444031]])

In [29]:
np.random.randint(34,100)

62

In [32]:
np.random.randint(20,34,100)

array([29, 27, 29, 33, 29, 22, 32, 28, 33, 26, 27, 28, 28, 25, 21, 25, 30,
       23, 21, 28, 31, 33, 23, 24, 20, 28, 23, 27, 24, 21, 25, 33, 33, 28,
       30, 21, 20, 26, 30, 25, 29, 32, 29, 32, 27, 23, 25, 24, 24, 21, 28,
       22, 26, 23, 27, 28, 29, 31, 20, 26, 26, 33, 30, 27, 23, 20, 26, 21,
       32, 23, 29, 28, 30, 31, 26, 32, 33, 23, 29, 28, 31, 33, 24, 26, 24,
       32, 28, 25, 29, 23, 30, 27, 33, 29, 31, 32, 20, 31, 27, 23])

In [36]:
sample_array=np.arange(20)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [39]:
rand_array=np.random.randint(7,77,30)
rand_array

array([74, 36, 72, 10, 73, 73, 15, 33, 59, 17, 13, 16, 27, 40, 67, 10, 68,
       65, 29, 23, 57, 45, 22, 28, 64, 59, 64, 11, 57, 65])

In [41]:
sample_array.reshape(4,5)
              

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [42]:
sample_array.reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [43]:
sample_array.min()

0

In [44]:
sample_array.max()

19

In [45]:
rand_array.min()

10

In [46]:
rand_array.max()


74

In [47]:
rand_array.argmax()

0

In [48]:
rand_array.argmin()


3

In [49]:
##slicing


In [51]:
sample_array=np.arange(2,23)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22])

In [52]:
sample_array[3]

5

In [53]:
sample_array[3:7]

array([5, 6, 7, 8])

In [56]:
sample_array[2:8]=33
sample_array

array([ 2,  3, 33, 33, 33, 33, 33, 33, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22])

In [57]:
sample_array[:]=11
sample_array

array([11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 11])

In [58]:
### TWO DIMENSIONAL MATRIX###

In [62]:
sample_matrix=np.array(([1,2,3],[4,5,6],[7,8,9],[10,11,12]))
sample_matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [64]:
sample_matrix[2][2]
                 

9

In [67]:
sample_matrix[2:]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [69]:
sample_matrix[1][2]

6

In [73]:
sample_array=np.arange(1,25,2)
sample_array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [74]:
sample_array+sample_array

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46])

In [75]:
np.exp(sample_array)

array([2.71828183e+00, 2.00855369e+01, 1.48413159e+02, 1.09663316e+03,
       8.10308393e+03, 5.98741417e+04, 4.42413392e+05, 3.26901737e+06,
       2.41549528e+07, 1.78482301e+08, 1.31881573e+09, 9.74480345e+09])

In [76]:
np.sqrt(sample_array)

array([1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ,
       3.31662479, 3.60555128, 3.87298335, 4.12310563, 4.35889894,
       4.58257569, 4.79583152])

In [77]:
np.var(sample_array)

47.666666666666664

In [78]:
np.mean(sample_array)

12.0

In [80]:
sports=np.array(['golf','cricket','football','chess','golf','chess'])
np.unique(sports)

array(['chess', 'cricket', 'football', 'golf'], dtype='<U8')